### ISSUE TITLE
NPE from DirectTCP

### ISSUE THREAD

**Issue by moderakh** [Azure/azure-cosmosdb-java#144]
```
Caused by: GoneException{error=null, resourceAddress='/apps/82c32209-2f24-41fb-92da-6a5eeb11ab4e/services/82b603c7-91ad-4d4c-8876-c87b4290fb80/partitions/0ed10602-8ce1-4911-9bf2-141ca1db609d/replicas/132036402037835371p', statusCode=410, message=failed to establish connection to cdb-ms-prod-centralus1-fd11.documents.azure.com:14001: null, getCauseInfo=[class: class java.lang.NullPointerException, message: null], responseHeaders={x-ms-activity-id=af013050-8261-11e9-b123-0d272c2642db}, requestHeaders={authorization=type%3Dmaster%26ver%3D1.0%26sig%3D1mG9JTaOPSKo2cFdFvSqDeRG%2F7UMqKbH%2Fq0aNoGM%2FEk%3D, Accept=application/json, x-ms-date=Wed, 29 May 2019 22:32:47 GMT, x-ms-documentdb-collection-rid=gNQyAKDWGh0=, x-ms-client-retry-attempt-count=1, x-ms-documentdb-partitionkey=[230.0], x-ms-remaining-time-in-ms-on-client=51000, x-ms-consistency-level=Strong, Content-Type=application/json}}
	at com.microsoft.azure.cosmosdb.internal.directconnectivity.rntbd.RntbdServiceEndpoint.lambda$write$3(RntbdServiceEndpoint.java:220)
	... 48 more
Caused by: java.lang.NullPointerException
	at com.microsoft.azure.cosmosdb.internal.directconnectivity.rntbd.RntbdClientChannelPool.pendingRequestCount(RntbdClientChannelPool.java:207)
	at com.microsoft.azure.cosmosdb.internal.directconnectivity.rntbd.RntbdClientChannelPool.lambda$pollChannel$0(RntbdClientChannelPool.java:164)
	at java.util.concurrent.ConcurrentHashMap$SearchMappingsTask.compute(ConcurrentHashMap.java:5309)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
	at java.util.concurrent.ConcurrentHashMap.search(ConcurrentHashMap.java:3704)
	at com.microsoft.azure.cosmosdb.internal.directconnectivity.rntbd.RntbdClientChannelPool.pollChannel(RntbdClientChannelPool.java:163)
	at io.netty.channel.pool.SimpleChannelPool.acquireHealthyFromPoolOrNew(SimpleChannelPool.java:174)
	... 38 more
```

more details here:
https://dev.azure.com/azure-cosmos-java/azure-cosmos-java/_build/results?buildId=198

**Comment by moderakh** [comment]
log attached.
[log_7_198.zip](https://github.com/Azure/azure-cosmosdb-java/files/3234812/log_7_198.zip)
