### ISSUE TITLE
java.lang.NoClassDefFoundError from TCP

### ISSUE THREAD

**Issue by moderakh** [Azure/azure-cosmosdb-java#145]
```
2019-05-29 22:32:56,986       [CosmosEventLoop-5-2] WARN  io.netty.channel.AbstractChannelHandlerContext - An exception 'java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.azure.cosmosdb.internal.directconnectivity.rntbd.RntbdReporter' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
io.netty.handler.timeout.WriteTimeoutException
2019-05-29 22:32:56,986       [CosmosEventLoop-5-2] WARN  com.microsoft.azure.cosmosdb.internal.directconnectivity.RntbdTransportClient - [com.microsoft.azure.cosmosdb.internal.directconnectivity.rntbd.RntbdRequestArgs(aeee1dff-8261-11e9-b123-0d272c2642db, origin: rntbd://cdb-ms-prod-centralus1-fd11.documents.azure.com:14001, operationType: Create, resourceType: Document, replicaPath: /apps/82c32209-2f24-41fb-92da-6a5eeb11ab4e/services/82b603c7-91ad-4d4c-8876-c87b4290fb80/partitions/0ed10602-8ce1-4911-9bf2-141ca1db609d/replicas/132036402037835371p, lifetime: PT10.0068553S)] expected failure of class com.microsoft.azure.cosmosdb.DocumentClientException, not 
java.util.concurrent.CompletionException: GoneException{error=null, resourceAddress='rntbd:/cdb-ms-prod-centralus1-fd11.documents.azure.com/13.89.170.4:14001/apps/82c32209-2f24-41fb-92da-6a5eeb11ab4e/services/82b603c7-91ad-4d4c-8876-c87b4290fb80/partitions/0ed10602-8ce1-4911-9bf2-141ca1db609d/replicas/132036402037835371p', statusCode=410, message=[id: 0x4ef1b7d5, L:0.0.0.0/0.0.0.0:51598 ! R:cdb-ms-prod-centralus1-fd11.documents.azure.com/13.89.170.4:14001] context request failed with 15 pending requests, getCauseInfo=[class: class io.netty.channel.ChannelException, message: context send failed due to java.util.concurrent.ExecutionException: javax.net.ssl.SSLException: SSLEngine closed already], responseHeaders={authorization=type%3Dmaster%26ver%3D1.0%26sig%3D2QoTGEn7AH%2BOnRZfQvcMKCUhbIX0bVJbbGXzUpoMpOg%3D, Accept=application/json, x-ms-date=Wed, 29 May 2019 22:32:46 GMT, x-ms-documentdb-collection-rid=gNQyAKDWGh0=, x-ms-client-retry-attempt-count=0, x-ms-documentdb-partitionkey=[106.0], x-ms-remaining-time-in-ms-on-client=60000, x-ms-consistency-level=Strong, Content-Type=application/json}, requestHeaders={authorization=type%3Dmaster%26ver%3D1.0%26sig%3D2QoTGEn7AH%2BOnRZfQvcMKCUhbIX0bVJbbGXzUpoMpOg%3D, Accept=application/json, x-ms-date=Wed, 29 May 2019 22:32:46 GMT, x-ms-documentdb-collection-rid=gNQyAKDWGh0=, x-ms-client-retry-attempt-count=0, x-ms-documentdb-partitionkey=[106.0], x-ms-remaining-time-in-ms-on-client=60000, x-ms-consistency-level=Strong, Content-Type=application/json}}
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:769)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at com.microsoft.azure.cosmosdb.internal.directconnectivity.rntbd.RntbdRequestManager.completeAllPendingRequestsExceptionally(RntbdRequestManager.java:559)
	at com.microsoft.azure.cosmosdb.internal.directconnectivity.rntbd.RntbdRequestManager.channelInactive(RntbdRequestManager.java:154)
```

more detail here:
https://dev.azure.com/azure-cosmos-java/azure-cosmos-java/_build/results?buildId=198

**Comment by moderakh** [comment]
log attached
[log_7_198.zip](https://github.com/Azure/azure-cosmosdb-java/files/3234830/log_7_198.zip)

**Comment by moderakh** [comment]
this one accompanies with 
```
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 1660944391, max: 1670381568)
```
not sure if that's related or just a co-incident.
